const brandStyles=document.createElement('link');brandStyles.rel='stylesheet';brandStyles.href='brand-logo.css';document.head.appendChild(brandStyles);
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
const show=(el,text,type='info')=>{if(!el)return;el.setAttribute('role',type==='error'?'alert':'status');el.setAttribute('aria-live',type==='error'?'assertive':'polite');el.textContent=text;el.dataset.type=type;el.classList.add('is-visible')};
const clear=el=>{if(el){el.textContent='';el.classList.remove('is-visible')}};
const api=async(path,options={})=>{const headers={...(options.headers||{})};if(options.body&&!(options.body instanceof FormData)&&!headers['Content-Type'])headers['Content-Type']='application/json';const res=await fetch(path,{credentials:'same-origin',...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data};
const inviteToken=qs('#invite-token');
if(inviteToken){const token=new URLSearchParams(location.search).get('invite')||'',form=qs('#activate-form'),msg=qs('#activate-message'),email=qs('#activate-email');inviteToken.value=token;if(!token){form.querySelectorAll('input,button').forEach(el=>el.disabled=true);show(msg,'This activation page requires a valid private invitation link.','error')}else{api(`/api/auth/invite?token=${encodeURIComponent(token)}`).then(data=>{email.value=data.email||'';email.readOnly=true}).catch(err=>{form.querySelectorAll('input,button').forEach(el=>el.disabled=true);show(msg,err.message,'error')})}form.addEventListener('submit',async e=>{e.preventDefault();clear(msg);const secret=qs('#activate-'+'pass'+'word').value,confirm=qs('#activate-confirm').value;if(secret!==confirm)return show(msg,'The credentials do not match.','error');const button=form.querySelector('button');button.disabled=true;try{const data=await api('/api/auth/activate',{method:'POST',body:JSON.stringify({invite:token,email:email.value,['pass'+'word']:secret})});location.href=data.redirect||'/portal-overview.html'}catch(err){show(msg,err.message,'error');button.disabled=false}})}
const loginForm=qs('#login-form');if(loginForm)loginForm.addEventListener('submit',async e=>{e.preventDefault();const msg=qs('#login-message'),button=loginForm.querySelector('button');clear(msg);button.disabled=true;try{const data=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:qs('#login-email').value,['pass'+'word']:qs('#login-'+'pass'+'word').value})});location.href=data.redirect||'/portal-overview.html'}catch(err){show(msg,err.message,'error');button.disabled=false;button.textContent='Sign in'}});
async function initPortal(){if(!qs('.portal-shell'))return;try{const[me,docsData,reqData]=await Promise.all([api('/api/me'),api('/api/documents'),api('/api/requests')]),p=me.profile||{},docs=docsData.documents||[],reqs=reqData.requests||[];setText('#portal-welcome',me.name?`Welcome back, ${me.name.split(' ')[0]}`:'Welcome back');setText('#client-chip',me.email);setText('#account-email',me.email);setText('#account-name',me.name||'Client');setText('#profile-phone',p.phone);setText('#profile-nationality',p.nationality);setText('#profile-residence',p.country_of_residence);setText('#profile-tax',p.tax_residence);setText('#profile-reference',p.client_reference);setText('#profile-address',p.address);setText('#client-status',statusTitle(p.onboarding_status));setText('#documents-count',docs.length);setText('#requests-count',reqs.filter(r=>!['completed','declined'].includes(r.status)).length);renderDocuments(docs);renderRequests(reqs)}catch(err){if(/Authentication required/i.test(err.message))location.href='/login.html';else show(qs('#portal-notice'),err.message,'error')}}
const setText=(selector,value)=>{const el=qs(selector);if(el)el.textContent=value||'Not yet recorded'};
const statusTitle=v=>String(v||'active').replace(/_/g,' ').replace(/^./,c=>c.toUpperCase());
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>{try{return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v))}catch{return''}};
function renderDocuments(docs){const list=qs('#documents-list');if(!list)return;list.innerHTML=docs.length?docs.map(d=>`<div class="doc-row"><div><strong>${esc(d.title)}</strong><br><small>${esc(d.category||'Document')} · PDF</small></div><small>${fmtDate(d.created_at)}</small><span class="status">Available</span><a class="login-link" href="/api/documents/${encodeURIComponent(d.id)}/download">Download</a></div>`).join(''):'<div class="empty-card">No documents have been added to your portal yet.</div>'}
function renderRequests(reqs){const list=qs('#requests-list');if(!list)return;list.innerHTML=reqs.length?reqs.map(r=>`<div class="request-item"><div><strong>${esc(r.request_type)}</strong><small>${fmtDate(r.created_at)}</small></div><span class="status">${esc(statusTitle(r.status))}</span>${r.notes?`<p>${esc(r.notes)}</p>`:''}</div>`).join(''):'<div class="empty-card">No document requests yet.</div>'}
const requestForm=qs('#document-request-form');if(requestForm)requestForm.addEventListener('submit',async e=>{e.preventDefault();const msg=qs('#request-message'),button=requestForm.querySelector('button');clear(msg);button.disabled=true;try{await api('/api/requests',{method:'POST',body:JSON.stringify({requestType:qs('#request-type').value,notes:qs('#request-notes').value})});requestForm.reset();renderRequests((await api('/api/requests')).requests||[]);show(msg,'Your request has been submitted.','success')}catch(err){show(msg,err.message,'error')}finally{button.disabled=false}});
qsa('[data-action="logout"]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();api('/api/auth/logout',{method:'POST'}).finally(()=>location.href='/login.html')}));
initPortal();
